version: '3'

services:
  dev:
    build:
      dockerfile: support/dev/Dockerfile
      context: .
    working_dir: /work
    command: support/dev/run
    volumes:
      - .:/work
      - stack-global:/root/.stack
    depends_on:
      - database

  database:
    image: postgres:10.3
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: tododb
    ports:
      - 5432:5432

volumes:
  stack-global:
    external: true
