name:                haskell-todo-mvc
version:             0.1.0.0
github:              "githubuser/haskell-todo-mvc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Widentities
- -Wredundant-constraints
- -Wmonomorphism-restriction

description: Todo mvc practice app

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-server
    - aeson
    - wai
    - warp
    - monad-logger
    - mtl
    - transformers
    - persistent
    - persistent-template
    - persistent-postgresql
    - bifunctors
    - bytestring

executables:
  haskell-todo-mvc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-todo-mvc
    - monad-logger
    - persistent
    - persistent-postgresql

tests:
  haskell-todo-mvc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-todo-mvc
