version: '3'

services:
  dev:
    build:
      dockerfile: support/dev/Dockerfile
      context: .
    working_dir: /work
    command: support/dev/run
    ports:
      - 8080:8080
      - 4008:4008
    volumes:
      - .:/work
      - yarn-cache:/tmp/yarn-cache

volumes:
  yarn-cache:
    external: true
